-- deDE.lua
local L = LibStub("AceLocale-3.0"):NewLocale("TipTacMSP", "deDE")
if not L then return end

-- Text für den Tooltip
L["undefined"] = "undefiniert";
L["Normal"] = "Normal";
L["Casual"] = "Durchschnittlich";
L["Full-Time"] = "Vollzeit";
L["Beginner"] = "Anfänger";
L["out of Character"] = "Outtime";
L["in Character"] = "Intime";
L["Looking For Contact"] = "Suche nach Kontakt";
L["Storyteller"] = "Spielleiter";
L["MSP-Name"] = "MSP-Name"
L["MSP-Status"] = "MSP-Status"
L["MSP-Style"] = "MSP-Stil"
L["MSP-Client"] = "MSP-Client"
L["MSP-Currently"] = "MSP-Aktuell";
L["MSP-Description"] = "MSP-Beschreibung";
L['No'] = "Nein";
L['Yes'] = "Ja";

-- Optionen
L["General"] = "Allgemein";
L["Show MSP Name"] = "Zeige MSP Namen";
L["Shows the MSP Name in the Game Tooltip."] = "Zeigt den MSP namen im Spieler-Tooltip";
L["Show MSP Status"] = "Zeige MSP Status";
L["Shows the MSP Status in the Game Tooltip."] = "Zeige den MSP-Status im Spieler-Tooltip";
L["Show MSP RP Style"] = "Zeige den MSP Rollenspiel-Stil";
L["Shows the MSP Roleplay Style in the Game Tooltip."] = "Zeigt den MSP Rollenspiel-Stil in dem Spieler-Tooltip";
L["Show MSP Client"] = "Zeige den MSP-Client";
L["Shows the MSP Client(s) in the Game Tooltip."] = "Zeigt den MSP-Client im Spieler-Tooltip";

-- Text für die Optionen (core)
L["Enable ChatFrame Hover Hyperlinks"] = "Aktiviere das Mouseover im Chat für Links";
L["Tip Update Frequency"] = "Aktualisierungsfrequenz";
L["GameTooltip Scale"] = "Skalierung des Spieltooltips";
L["Targeting You Text"] = "Text die auf dich zielen.";
L["Show Unit Target"] = "Zeile Einheitenziele";
L["Show Unit Realm"] = "Zeige den Realm";
L["Name Type"] = "Zeige den Typ";
L["Show Player Gender"] = "Zeige das Geschlecht";
L["Show Who Targets the Unit"] = "Zeige wer das Ziel noch im Ziel hat";
L["Show Player Guild Rank Title"] = "Zeige den Rang in der Gilde";
L["Show DC, AFK and DND Status"] = "Zeige DC, AFK und DND Status";
L["Enable TipTac Unit Tip Appearance"] = "Aktiviere TipTac Einheiten";
L["Shows the MSP Client(s) in the Game Tooltip."] = "Zeige den MSP-Client im Spielertooltip";
L["Show MSP Client"] = "Zeige MSP-Client";
L["Shows the MSP Roleplay Style in the Game Tooltip."] = "Zeige den MSP-Rollenspielstil";
L["Show MSP RP Style"] = "Zeige den RP-Stil";
L["Shows the MSP Status in the Game Tooltip."] = "Zeigt den MSP-Status von dem Spielertooltip";
L["Show MSP Status"] = "Zeige MSP-Status";
L["Shows the MSP Name in the Game Tooltip."] = "Zeigt den MSP-Namen im Spielertooltip";
L["Show MSP Name"] = "Zeige MSP-Name";
L["Still Show Hidden Tips when Holding Shift"] = "Zeige versteckte Toolips wenn Umschalt gedrückt wurde";
L["Hide Unit Tips for Unit Frames in Combat"] = "Verberge alle Einheitentooltips im Kampf";
L["Hide All Unit Tips in Combat"] = "Verstecke alle Einheitentooltips im kampf";
L["Mouse Anchor Y Offset"] = "Mausversatz in Y-Richtung";
L["Mouse Anchor X Offset"] = "Mausversatz in X-Richtung";
L["Frame Tip Point"] = "Frame Tip Punkt";
L["Frame Tip Type"] = "Frame Tip Typ";
L["Frame Unit Point"] = "Frame Einheit Punkt";
L["Frame Unit Type"] = "Frame Einheit Typ";
L["World Tip Point"] = "Welt Tip Punkt";
L["World Tip Type"] = "Welt Tip Typ";
L["World Unit Point"] = "Welt Einheit Punkt";
L["World Unit Type"] = "Welt Einheit Typ";
L["Icon Dimension"] = "Icongröße";
L["Icon Anchor"] = "Iconposition";
L["Show Combat Icon"] = "Zeige Kampficons";
L["Show Faction Icon"] = "Zeige Fraktionsicon";
L["Show Raid Icon"] = "Zeige Raid-Icon";
L["No Cooldown Count Text"] = "Kein Cooldown Count Text";
L["Show Cooldown Models"] = "Zeige Cooldowns";
L["Max Aura Rows"] = "Max. Zeilen an Auren";
L["Aura Icon Dimension"] = "Größe von Auren";
L["Only Show Auras Coming from You"] = "Zeige nur Auren die du gezaubert hast.";
L["Show Unit Debuffs"] = "Zeige Debuffs";
L["Show Unit Buffs"] = "Zeige Buffs";
L["Put Aura Icons at the Bottom Instead of Top"] = "Zeige die Auren unten anstatt oben";
L["Power Bar Text"] = "Power-Bar Text";
L["Show Energy, Rage, Runic Power or Focus Bar"] = "Zeige Energie, Wut, Runen oder Fokus als Balken";
L["Mana Bar Color"] = "Farbe des Manabalkens";
L["Mana Bar Text"] = "Zeige Text auf dem Manabalken";
L["Show Mana Bar"] = "Zeige Manabalken";
L["Health Bar Color"] = "Farbe von Gesundheit";
L["Class Colored Health Bar"] = "Klassenfarbe für Gesundheitsbalken";
L["Health Bar Text"] = "Gesundheit als Text";
L["Show Health Bar"] = "Zeige Gesundheitsbalken";
L["Show Condensed Bar Values"] = "Zusammengefasste Werte";
L["Hide the Default Health Bar"] = "Verberge die Standardgesundheitsbalken";
L["Bar Height"] = "Balkenehöhe";
L["Bar Texture"] = "Textur des Balkens";
L["Font Size"] = "Schriftgröße";
L["Font Flags"] = "Schrifteigenschaften";
L["Font Face"] = "SChriftart";
L["Instantly Hide World Frame Tips"] = "Sofortiges ausblenden der Tooltips";
L["Fadeout Time"] = "Ausblendzeit";
L["Prefade Time"] = "Einblendzeit";
L["Override Default GameTooltip Fade"] = "Übergehe Standardein/ausblenden des Spieltooltips";
L["Boss"] = "Boss";
L["Rare Elite"] = "Rar Elite";
L["Rare"] = "Rar";
L["Elite"] = "Elite";
L["Normal"] = "Normal";
L["Trivial"] = "Trivial";
L["Minus"] = "Minus";
L["Font Size Delta"] = "Schriftgrößenunterschied";
L["Modify the GameTooltip Font Templates"] = "Modifiziere die Schriftart des Spieltooltips";
L["Gradient Color"] = "Farbe für Verlauf";
L["Show Gradient Tooltips"] = "Zeige Tooltips mit Farbverlauf";
L["Tip Border Color"] = "Tooltip Rahmenfarbe";
L["Tip Background Color"] = "Tooltip Hintergrundfarbe";
L["Backdrop Insets"] = "Backdrop Insets";
L["Backdrop Edge Size"] = "Backdrop Eckengröße";
L["Border Texture"] = "Rahmentextur";
L["Background Texture"] = "Hintergrundtextur";
L["Dead Color"] = "Farbe für tot";
L["Friendly Player Color"] = "Farbe für freundlichen Spieler";
L["Friendly NPC or PvP Player Color"] = "Freundlicher NPC oder PvP-Spieler";
L["Neutral Color"] = "Neutrale Farbe";
L["Caution Color"] = "Achtung Farbe";
L["Hostile Color"] = "Geisel Farbe";
L["Tapped Color"] = "Farbe fpür getappt";
L["Color border based on the unit's reaction"] = "Farbumrandung absiert auf Einheitenverhalten";
L["Color backdrop based on the unit's reaction"] = "farbhintergrund basiert auf der Reaktion der Einheit";
L["Show the unit's reaction as text"] = "Zeige die Reaktion der Einheit im Text";
L["Color Tip Border by Class Color"] = "Färbt die Umrandung anhand der Klasse der Einheit";
L["Color Player Names by Class Color"] = "Färbe Namen anhand der Klasse";
L["Neutral Level Color"] = "Farbe für Level";
L["Race & Creature Type Color"] = "Farbe für Rasse und Kraeturenart";
L["Same Guild Color"] = "Farbe für gleiche Gilde";
L["Guild Color"] = "Gildenfarbe";
L["Color Guild by Reaction"] = "Färbe den Gildennamen nach Reaktion";
L["Hide Faction Text"] = "Verstecke Fraktionstext";

-- Gruppen in den Optionen
L["General"] = "Generell";
L["MSP"] = "MSP";
L["Special"] = "Spezial";
L["Colors"] = "Farben";
L["Reactions"] = "Reaktionen";
L["BG Color"] = "HG Farben";
L["Backdrop"] = "Hintergrund";
L["Font"] = "Schrift";
L["Classify"] = "Klassifizierung";
L["Fading"] = "Ausblenden";
L["Bars"] = "Balken";
L["Bar Types"] = "Balkentyp";
L["Auras"] = "Auren";
L["Icon"] = "Icon";
L["Anchors"] = "Anker";
L["Mouse"] = "Maus";
L["Combat"] = "Kampf";