-- enUS.lua
local L = LibStub("AceLocale-3.0"):NewLocale("TipTacMSP", "enUS", true)

--Text für den tooltip
L["undefined"] = true;
L["Normal"] = true;
L["Casual"] = true;
L["Full-Time"] = true;
L["Beginner"] = true;
L["out of Character"] = true;
L["in Character"] = true;
L["Looking For Contact"] = true;
L["Storyteller"] = true;
L["MSP-Name"] = true
L["MSP-Status"] = true
L["MSP-Style"] = true
L["MSP-Client"] = true
L["MSP-Currently"] = true;
L["MSP-Description"] = true;
L['No'] = true;
L['Yes'] = true;

-- Text für die Optionen (MSP)
L["General"] = true;
L["Show MSP Name"] = true
L["Shows the MSP Name in the Game Tooltip."] = true
L["Show MSP Status"] = true
L["Shows the MSP Status in the Game Tooltip."] = true
L["Show MSP RP Style"] = true
L["Shows the MSP Roleplay Style in the Game Tooltip."] = true
L["Show MSP Client"] = true
L["Shows the MSP Client(s) in the Game Tooltip."] = true
L["Show MSP Currently"] = true;
L["Shows the text in the Field for current."] = true;
L["Show MSP Physical Description exists"] = true;
L["Shows the Information of a detailed Physical Description exists."] = true;

-- Text für die Optionen (core)
L["Enable ChatFrame Hover Hyperlinks"] = true;
L["Tip Update Frequency"] = true;
L["GameTooltip Scale"] = true;
L["Targeting You Text"] = true;
L["Show Unit Target"] = true;
L["Show Unit Realm"] = true;
L["Name Type"] = true;
L["Show Player Gender"] = true;
L["Show Who Targets the Unit"] = true;
L["Show Player Guild Rank Title"] = true;
L["Show DC, AFK and DND Status"] = true;
L["Enable TipTac Unit Tip Appearance"] = true;
L["Shows the MSP Client(s) in the Game Tooltip."] = true;
L["Show MSP Client"] = true;
L["Shows the MSP Roleplay Style in the Game Tooltip."] = true;
L["Show MSP RP Style"] = true;
L["Shows the MSP Status in the Game Tooltip."] = true;
L["Show MSP Status"] = true;
L["Shows the MSP Name in the Game Tooltip."] = true;
L["Show MSP Name"] = true;
L["Still Show Hidden Tips when Holding Shift"] = true;
L["Hide Unit Tips for Unit Frames in Combat"] = true;
L["Hide All Unit Tips in Combat"] = true;
L["Mouse Anchor Y Offset"] = true;
L["Mouse Anchor X Offset"] = true;
L["Frame Tip Point"] = true;
L["Frame Tip Type"] = true;
L["Frame Unit Point"] = true;
L["Frame Unit Type"] = true;
L["World Tip Point"] = true;
L["World Tip Type"] = true;
L["World Unit Point"] = true;
L["World Unit Type"] = true;
L["Icon Dimension"] = true;
L["Icon Anchor"] = true;
L["Show Combat Icon"] = true;
L["Show Faction Icon"] = true;
L["Show Raid Icon"] = true;
L["No Cooldown Count Text"] = true;
L["Show Cooldown Models"] = true;
L["Max Aura Rows"] = true;
L["Aura Icon Dimension"] = true;
L["Only Show Auras Coming from You"] = true;
L["Show Unit Debuffs"] = true;
L["Show Unit Buffs"] = true;
L["Put Aura Icons at the Bottom Instead of Top"] = true;
L["Power Bar Text"] = true;
L["Show Energy, Rage, Runic Power or Focus Bar"] = true;
L["Mana Bar Color"] = true;
L["Mana Bar Text"] = true;
L["Show Mana Bar"] = true;
L["Health Bar Color"] = true;
L["Class Colored Health Bar"] = true;
L["Health Bar Text"] = true;
L["Show Health Bar"] = true;
L["Show Condensed Bar Values"] = true;
L["Hide the Default Health Bar"] = true;
L["Bar Height"] = true;
L["Bar Texture"] = true;
L["Font Size"] = true;
L["Font Flags"] = true;
L["Font Face"] = true;
L["Instantly Hide World Frame Tips"] = true;
L["Fadeout Time"] = true;
L["Prefade Time"] = true;
L["Override Default GameTooltip Fade"] = true;
L["Boss"] = true;
L["Rare Elite"] = true;
L["Rare"] = true;
L["Elite"] = true;
L["Normal"] = true;
L["Trivial"] = true;
L["Minus"] = true;
L["Font Size Delta"] = true;
L["Modify the GameTooltip Font Templates"] = true;
L["Gradient Color"] = true;
L["Show Gradient Tooltips"] = true;
L["Tip Border Color"] = true;
L["Tip Background Color"] = true;
L["Backdrop Insets"] = true;
L["Backdrop Edge Size"] = true;
L["Border Texture"] = true;
L["Background Texture"] = true;
L["Dead Color"] = true;
L["Friendly Player Color"] = true;
L["Friendly NPC or PvP Player Color"] = true;
L["Neutral Color"] = true;
L["Caution Color"] = true;
L["Hostile Color"] = true;
L["Tapped Color"] = true;
L["Color border based on the unit's reaction"] = true;
L["Color backdrop based on the unit's reaction"] = true;
L["Show the unit's reaction as text"] = true;
L["Color Tip Border by Class Color"] = true;
L["Color Player Names by Class Color"] = true;
L["Neutral Level Color"] = true;
L["Race & Creature Type Color"] = true;
L["Same Guild Color"] = true;
L["Guild Color"] = true;
L["Color Guild by Reaction"] = true;
L["Hide Faction Text"] = true;

-- Gruppen in den Optionen
L["General"] = true;
L["MSP"] = true;
L["Special"] = true;
L["Colors"] = true;
L["Reactions"] = true;
L["BG Color"] = true;
L["Backdrop"] = true;
L["Font"] = true;
L["Classify"] = true;
L["Fading"] = true;
L["Bars"] = true;
L["Bar Types"] = true;
L["Auras"] = true;
L["Icon"] = true;
L["Anchors"] = true;
L["Mouse"] = true;
L["Combat"] = true;