--[=[
HealersHaveToDie World of Warcraft Add-on
Copyright (c) 2009-2013 by John Wellesz (Archarodim@teaser.fr)
All rights reserved

Version 2.1.4

This is a very simple and light add-on that rings when you hover or target a
unit of the opposite faction who healed someone during the last 60 seconds (can
be configured).
Now you can spot those nasty healers instantly and help them to accomplish their destiny!

This add-on uses the Ace3 framework.

type /hhtd to get a list of existing options.

-----
    Localization.lua
-----


--]=]


--[=[
--                      YOUR ATTENTION PLEASE
--
--         !!!!!!! TRANSLATORS TRANSLATORS TRANSLATORS !!!!!!!
--
--    Thank you very much for your interest in translating Healers Have To Die.
--    Do not edit this file. Use the localization interface available at the following address:
--
--      ##########################################################################
--      #  http://wow.curseforge.com/projects/healers-have-to-die/localization/  #
--      ##########################################################################
--
--    Your translations made using this interface will be automatically included in the next release.
--
--]=]


do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "enUS", true, true);

    if L then
        L["ACTIVE"] = "Active!"
L["Announcer"] = "Announcer"
L["Announcer_DESC"] = "This module allows you to manage chat and sound alerts"
L["AUTO_RAID_PARTY_INSTANCE"] = "Auto: Raid/Party/Instance"
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "The announce to raid messages are not configured. Type /HHTDG"
L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = "It's too soon (see the announce throttle setting)."
L["CHAT_POST_NO_HEALERS"] = "No healers on either sides :/ (yet)"
L["DESCRIPTION"] = "Spot those bloody healers instantly and help them accomplish their destiny! (PVP and PVE)"
L["DISABLED"] = [=[hhtd has been disabled!
Type '/hhtd on' to re-enable it.]=]
L["ENABLED"] = "enabled! Type /HHTDG to open its option panel"
L["HEALER_UNDER_ATTACK"] = "Healer friend %s is being attacked by %s"
L["HUMAN"] = "Human"
L["IDLE"] = "Idle"
L["INSTANCE_CHAT"] = "Instance chat"
L["IS_A_HEALER"] = "%s is a healer!"
L["LOG_ACTIVE"] = "Active!"
L["LOG_BELOW_THRESHOLD"] = " (below threshold)"
L["LOG_IDLE"] = "Idle"
L["NO_DATA"] = "No data"
L["NPC"] = "NPC"
L["NPH"] = "Name Plate Hooker"
L["NPH_DESC"] = "This module adds a red cross to enemy healers' name plates"
L["OPT_ANNOUNCE"] = "Show messages"
L["OPT_ANNOUNCE_DESC"] = "HHTD will display messages when you target or mouse-over an enemy healer."
L["OPT_CLEAR_LOGS"] = "Clear logs"
L["OPT_CORE_OPTIONS"] = "Core options"
L["OPT_DEBUG"] = "debugging logs"
L["OPT_DEBUG_DESC"] = "Enables / disables debugging"
L["OPT_DEBUGLEVEL"] = "debugging level"
L["OPT_DEBUGLEVEL_DESC"] = "debug level: 1=all, 2=warnings, 3=errors"
L["OPT_ENABLE_GEHR"] = "Enable Graphical Reporter"
L["OPT_ENABLE_GEHR_DESC"] = "Displays a graphical list of detected enemy healers with various features"
L["OPT_HEALER_FORGET_TIMER"] = "Healer Forget Timer"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Set the Healer Forget Timer (the time in seconds an enemy will remain considered has a healer)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "Heal amount (|cff00dd00%u|r) threshold"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Healers won't be detected until they reach this cumulative amount of healing based on a percentage of your own maximum health."
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "Protect friendly healers"
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "Display an alert when a nearby friendly healers is attacked"
L["OPT_LOG"] = "Logging"
L["OPT_LOG_DESC"] = "Enables logging and adds a new 'Logs' tab to HHTD's option panel"
L["OPT_LOGS"] = "Logs"
L["OPT_LOGS_DESC"] = "Display HHTD detected healers and statistics"
L["OPT_MODULES"] = "Modules"
L["OPT_NPH_MARKER_SCALE"] = "Markers' scaling"
L["OPT_NPH_MARKER_SCALE_DESC"] = "Change markers' size"
L["OPT_NPH_MARKER_SETTINGS"] = "Markers' settings"
L["OPT_NPH_MARKER_X_OFFSET"] = "Horizontal offset"
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "Move markers horizontally"
L["OPT_NPH_MARKER_Y_OFFSET"] = "Vertical offset"
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "Move markers vertically"
L["OPT_NPH_WARNING1"] = [=[WARNING: Enemies' name-plates are currently disabled. HHTD cannot add its red cross symbol.
You can enable name-plates display through the WoW UI's options or by using the assigned key-stroke.]=]
L["OPT_NPH_WARNING2"] = [=[WARNING: Allies' name-plates are currently disabled. HHTD cannot add its healer symbol.
You can enable name-plates display through the WoW UI's options or by using the assigned key-stroke.]=]
L["OPT_OFF"] = "off"
L["OPT_OFF_DESC"] = "Disables HHTD"
L["OPT_ON"] = "on"
L["OPT_ON_DESC"] = "Enables HHTD"
L["OPT_POST_ANNOUNCE_CHANNEL"] = "Post channel"
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "Decide where your announce will be posted"
L["OPT_POST_ANNOUNCE_DESCRIPTION"] = [=[|cFFFF0000IMPORTANT:|r Type |cff40ff40/hhtdp|r or bind a key to announce friendly healers to protect and enemy healers to focus.

(see World of Warcraft escape menu binding interface to bind a key)
]=]
L["OPT_POST_ANNOUNCE_ENABLE"] = "Chat announces"
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "Enable announce to raid features."
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "Humans only"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "Do not include NPCs in the announce."
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "Text for enemy healers"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = [=[Type a message inciting your team to focus enemy healers.

You must use the [HEALERS] keyword somewhere which will be automatically replaced by the names of the currently active healers.]=]
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "There is one message for friends and one for foes, they cannot be the same."
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "Your message is too short!"
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "The [HEALERS] keyword is missing!"
L["OPT_POST_ANNOUNCE_NUMBER"] = "Healers number"
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "Set how many healers to include in each announce."
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "There is something wrong with one of the announce text."
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "Text for friendly healers"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = [=[Type a message inciting your team to protect their healers.

You must use the [HEALERS] keyword somewhere which will be automatically replaced by the names of the currently active healers.]=]
L["OPT_POST_ANNOUNCE_SETTINGS"] = "Announce to raid settings"
L["OPT_POST_ANNOUNCE_THROTTLE"] = "Announce throttle"
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "Set the minimum time in seconds between each possible announce."
L["OPT_PVE"] = "Enable for PVE"
L["OPT_PVE_DESC"] = "HHTD will also work for NPCs."
L["OPT_PVPHEALERSSPECSONLY"] = "Healer specialization detection"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "Only detect players specialized in healing. (this disables minimum heal amount filter for PVP)"
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "Set friendly healers role"
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "Will automatically set the raid HEALER role to friendly healers upon detection (if possible)"
L["OPT_SOUNDS"] = "Sound alerts"
L["OPT_SOUNDS_DESC"] = "HHTD will play a specific sound when you hover or target an enemy healer"
L["OPT_STRICTGUIDPVE"] = "Accurate PVE detection"
L["OPT_STRICTGUIDPVE_DESC"] = "When several NPCs share the same name, HHTD will only add a cross over those who actually healed instead of adding a cross to all of them. Note that most of the time, you'll need to target or mouse-over the unit for the cross to appear."
L["OPT_TESTONTARGET"] = "Test HHTD's behavior on current target"
L["OPT_TESTONTARGET_DESC"] = "Will mark your current target as a healer so you can test what happens."
L["OPT_TESTONTARGET_ENOTARGET"] = "You need to target something"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "Use minimum heal amount filter"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Healers will have to heal for a specified amount before being tagged as such."
L["OPT_VERSION"] = "version"
L["OPT_VERSION_DESC"] = "Display version and release date"
L["PARTY"] = "Party"
L["RELEASE_DATE"] = "Release Date:"
L["SAY"] = "Say"
L["VERSION"] = "version:"
L["YELL"] = "Yell"
L["YOU_GOT_HER"] = "You got %sher|r!"
L["YOU_GOT_HIM"] = "You got %shim|r!"
L["YOU_GOT_IT"] = "You got %sit|r!"


        

    end

end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "frFR");

    if L then
        L["ACTIVE"] = "Actif !"
L["Announcer"] = "Annonceur"
L["Announcer_DESC"] = "Ce module permet de gérer différents type d'alertes."
L["AUTO_RAID_PARTY_INSTANCE"] = "Automatique: Raid/Groupe/Instance"
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "Les messages d'annonce au raid ne sont pas configurés. Tapez /HHTDG"
L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = "C'est trop tôt (voir le réglage du limiteur d'annonce)"
L["CHAT_POST_NO_HEALERS"] = "Aucun soigneur d'un coté ou de l'autre :/ (pour l'instant)"
L["DESCRIPTION"] = "Débusquez ces maudits soigneurs instantanément et aider-les à accomplir leur destinée ! (JCJ et JCE)"
L["DISABLED"] = [=[hhtd a été désactivé !
Taper '/hhtd on' pour le réactiver]=]
L["ENABLED"] = "activé ! Taper /HHTDG pour accéder aux options"
L["HEALER_UNDER_ATTACK"] = "Le soigneur ami %s est attaqué par %s"
L["HUMAN"] = "Humain"
L["IDLE"] = "Dormant"
L["INSTANCE_CHAT"] = "Canal des instances"
L["IS_A_HEALER"] = "%s est un soigneur !"
L["LOG_ACTIVE"] = "Actif !"
L["LOG_BELOW_THRESHOLD"] = "(sous le seuil)"
L["LOG_IDLE"] = "Inactif"
L["NO_DATA"] = "Aucune donnée"
L["NPC"] = "PNJ"
L["NPH"] = "Barres d'info"
L["NPH_DESC"] = "Ce module ajoute une croix rouge au dessus des barres d'info des soigneurs ennemis."
L["OPT_ANNOUNCE"] = "Afficher les messages."
L["OPT_ANNOUNCE_DESC"] = "HHTD affiche des messages lorsque vous ciblez ou survolez des soigneurs ennemis avec la souris."
L["OPT_CLEAR_LOGS"] = "Effacer les journaux"
L["OPT_CORE_OPTIONS"] = "Options Générales"
L["OPT_DEBUG"] = "débuggage"
L["OPT_DEBUG_DESC"] = "Active / désactive le débuggage"
-- L["OPT_DEBUGLEVEL"] = ""
-- L["OPT_DEBUGLEVEL_DESC"] = ""
L["OPT_ENABLE_GEHR"] = "Activer le rapporteur graphique"
L["OPT_ENABLE_GEHR_DESC"] = "Affiche une interface listant les soigneurs ennemis."
L["OPT_HEALER_FORGET_TIMER"] = "Délai d'oubli des soigneurs"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Règle le délai d'oubli des soigneurs (le temps en secondes où un ennemi sera considéré comme soigneur)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "Seuil de soins (|cff00dd00%u|r)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Les soigneurs ne seront détectés qu'à partir de ce seuil de soin basé sur un pourcentage de vos points de vie maximales."
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "Protéger les soigneurs amicaux"
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "Affiche une alerte lorsqu'un soigneur amical proche est attaqué"
L["OPT_LOG"] = "Journalisation"
L["OPT_LOG_DESC"] = "Active la journalisation et ajoute un onglet 'Journaux' aux panneau des options de HHTD"
L["OPT_LOGS"] = "Journaux"
L["OPT_LOGS_DESC"] = "Affiche les soigneurs détectés par HHTD et des statistiques."
L["OPT_MODULES"] = "Modules"
L["OPT_NPH_MARKER_SCALE"] = "Échelle des marqueurs"
L["OPT_NPH_MARKER_SCALE_DESC"] = "Change la taille des marqueurs"
L["OPT_NPH_MARKER_SETTINGS"] = "Réglages des marqueurs"
L["OPT_NPH_MARKER_X_OFFSET"] = "Offset horizontale"
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "Déplacer les marqueurs horizontalement"
L["OPT_NPH_MARKER_Y_OFFSET"] = "Offset verticale"
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "Déplacer les marqueurs verticalement"
L["OPT_NPH_WARNING1"] = [=[ATTENTION : Les barres d'infos des unités ennemies sont désactivées. HHTD ne peut pas ajouter sa croix rouge.
Vous pouvez activer les barres d'infos dans les options d'interface de WoW ou en utilisant le raccourcis.]=]
L["OPT_NPH_WARNING2"] = [=[ATTENTION : Les barres d'infos des unités alliées sont désactivées. HHTD ne peut pas ajouter son symbole de soigneur.
Vous pouvez activer les barres d'infos dans les options d'interface de WoW ou en utilisant le raccourcis.]=]
L["OPT_OFF"] = "désactivé"
L["OPT_OFF_DESC"] = "Désactive HHTD"
L["OPT_ON"] = "activé"
L["OPT_ON_DESC"] = "Active HHTD"
L["OPT_POST_ANNOUNCE_CHANNEL"] = "Canal d'annonce"
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "Décider où votre annonce sera postée"
L["OPT_POST_ANNOUNCE_DESCRIPTION"] = [=[|cFFFF0000IMPORTANT:|r Tapez |cff40ff40/hhtdp|r ou utilisez un raccourci clavier pour annoncer les soigneurs amis à protéger et les soigneurs ennemis à focaliser.

(voir l'interface des raccourcis de World of Warcraft pour lier une touche à cette fonction)
]=]
L["OPT_POST_ANNOUNCE_ENABLE"] = "Annonces"
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "Activer les fonctionnalités d'annonce au raid."
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "Humains seulement"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "Ne pas inclure les PNJs dans l'annonce."
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "Texte pour les soigneurs ennemis"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = [=[Tapez un message incitant votre équipe à se focaliser sur les soigneurs ennemis.

Vous devez placer le mot clé [HEALERS] quelque part, il sera automatiquement remplacé par les noms des soigneurs actuellement actifs.]=]
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "Il y a un message pour les amis et un autre pour les ennemis, ils ne peuvent pas être identiques."
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "Votre message est trop court !"
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "Il manque le mot clé [HEALERS] !"
L["OPT_POST_ANNOUNCE_NUMBER"] = "Nombre de soigneurs."
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "Régler le nombre de soigneurs à inclure dans chacune des annonces."
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "Quelque chose ne va pas avec l'un de vos messages d'annonce."
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "Texte pour les soigneurs amis."
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = [=[Tapez un message incitant votre équipe à protéger ses soigneurs.

Vous devez placer le mot clé [HEALERS] quelque part, il sera automatiquement remplacé par les noms des soigneurs actuellement actifs.]=]
L["OPT_POST_ANNOUNCE_SETTINGS"] = "Réglages des annonces au raid."
L["OPT_POST_ANNOUNCE_THROTTLE"] = "Limiteur d'annonce"
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "Régler le temps minimum (en secondes) entre deux annonces."
L["OPT_PVE"] = "Activer en PVE"
L["OPT_PVE_DESC"] = "HHTD fonctionnera également avec les personnages non joueurs (PNJs)"
L["OPT_PVPHEALERSSPECSONLY"] = "Détection des spécialisations en soin"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "Ne détectera que les joueurs spécialisés en soins. (Cela désactive le filtrage sur les soins cumulés en PVP)"
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "Assignation des rôles"
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "Affectera automatiquement le rôle de soigneur aux joueurs détectés (si possible)"
L["OPT_SOUNDS"] = "Alertes sonores"
L["OPT_SOUNDS_DESC"] = "HHTD joue un son spécifique lorsque votre souris se trouve au dessus d'un soigneur ennemi ou lorsque vous en ciblez un."
L["OPT_STRICTGUIDPVE"] = "Détection PVE précise"
L["OPT_STRICTGUIDPVE_DESC"] = "Quand plusieurs PNJ partagent le même nom, HHTD n'ajoutera une croix qu'à ceux qui ont réellement soigné au lieu d'en ajouter une à tous. Notez qu'il vous faudra cibler ou survoler les unités avec la souris pour que les croix apparaissent."
L["OPT_TESTONTARGET"] = "Tester le comportement de HHTD sur la cible"
L["OPT_TESTONTARGET_DESC"] = "Marque la cible actuelle comme soigneur de façon à tester ce qui ce passe."
L["OPT_TESTONTARGET_ENOTARGET"] = "Vous devez cibler quelque chose."
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "Filtrage sur soins cumulés"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Les soigneurs devront cumuler un certain minimum de soins avant d'être considérés comme tel."
L["OPT_VERSION"] = "version"
L["OPT_VERSION_DESC"] = "Affiche la version et la date de sortie"
L["PARTY"] = "Groupe"
L["RELEASE_DATE"] = "Date de sortie :"
L["SAY"] = "Dire"
L["VERSION"] = "Version :"
L["YELL"] = "Crier"
L["YOU_GOT_HER"] = "Vous %sla|r tenez !"
L["YOU_GOT_HIM"] = "Vous %sle|r tenez !"
L["YOU_GOT_IT"] = "Vous %sle|r tenez !"

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "deDE");

    if L then
        L["ACTIVE"] = "Aktiv!" -- Needs review
L["Announcer"] = "Melder"
L["Announcer_DESC"] = "Dieses Modul erlaubt dir Chat-Warnungen und Alarmtöne einzustellen"
L["AUTO_RAID_PARTY_INSTANCE"] = "Auto: Schlachtzug/Gruppe/Instanz" -- Needs review
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "Die Texte für die Meldungen sind nicht konfiguriert. Tippe /hhtdg" -- Needs review
L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = "Das ist zu früh (siehe Option Verzögerung)." -- Needs review
L["CHAT_POST_NO_HEALERS"] = "Keine Heiler auf beiden Seiten :/ (noch)" -- Needs review
L["DESCRIPTION"] = "Entdecke auf der Stelle diese verdammten Heiler und sorge dafür daß sie Ihr Schicksal ereilt! (PVE und PVP)"
L["DISABLED"] = [=[hhtd wurde deaktiviert!
Gib /hhtd ein, um es wieder zu aktivieren.]=]
L["ENABLED"] = "aktiviert! Für eine Optionsliste gib /HHTDG ein." -- Needs review
L["HEALER_UNDER_ATTACK"] = "Heiler %s wird von %s angegriffen" -- Needs review
L["HUMAN"] = "Spieler" -- Needs review
L["IDLE"] = "Untätig" -- Needs review
L["INSTANCE_CHAT"] = "Instanz Chat" -- Needs review
L["IS_A_HEALER"] = "%s ist ein Heiler!"
L["LOG_ACTIVE"] = "Aktiv!" -- Needs review
L["LOG_BELOW_THRESHOLD"] = " (unter Schwellwert)" -- Needs review
L["LOG_IDLE"] = "inaktiv" -- Needs review
L["NO_DATA"] = "Keine Heilung" -- Needs review
-- L["NPC"] = ""
L["NPH"] = "Namensschildanker"
L["NPH_DESC"] = "Dieses Modul fügt den feindlichen Heilern ein rotes Kreuz auf den Namensschildern hinzu"
L["OPT_ANNOUNCE"] = "Mitteilungen anzeigen"
L["OPT_ANNOUNCE_DESC"] = "HHTD wird Mitteilungen anzeigen, wenn du auf einen feindlichen Heiler zielst oder die Maus über ihn bewegst."
L["OPT_CLEAR_LOGS"] = "Löschen" -- Needs review
L["OPT_CORE_OPTIONS"] = "Hauptoptionen"
L["OPT_DEBUG"] = "Fehler suchen"
L["OPT_DEBUG_DESC"] = "Fehlersuche aktivieren / deaktivieren"
L["OPT_DEBUGLEVEL"] = "Debug-Ebene" -- Needs review
L["OPT_DEBUGLEVEL_DESC"] = "Debug-Ebene: 1=Alle, 2=Warnungen, 3=Fehler" -- Needs review
L["OPT_ENABLE_GEHR"] = "Graphischen Bericht aktivieren"
L["OPT_ENABLE_GEHR_DESC"] = "Zeigt eine graphische Liste der entdeckten feindlichen Heiler mit verschiedenen Eigenschaften an."
L["OPT_HEALER_FORGET_TIMER"] = "\"Heiler-vergessen\" Timer"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Den \"Heiler-vergessen\" Timer einstellen (die Zeit in Sekunden, für deren Dauer ein Feind als Heiler betrachtet wird)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "Mindestmenge an gesamter Heilung (|cff00dd00%u|r)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Heiler werden nicht erkannt bis sie die \"Mindestmenge an gesamter Heilung\" erreicht haben."
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "Befreundete Heiler schützen" -- Needs review
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "Zeigt eine Warnung an, wenn ein befreundeter Heiler in der Nähe angegriffen wird." -- Needs review
L["OPT_LOG"] = "Protokollieren" -- Needs review
L["OPT_LOG_DESC"] = "Aktiviert die Protokollierung und fügt den Tab 'Protokolle' zum Optionsfenster hinzu." -- Needs review
L["OPT_LOGS"] = "Protokolle" -- Needs review
L["OPT_LOGS_DESC"] = "Zeigt erkannte Heiler und Statistik an." -- Needs review
L["OPT_MODULES"] = "Module"
L["OPT_NPH_MARKER_SCALE"] = "Symbolgröße" -- Needs review
L["OPT_NPH_MARKER_SCALE_DESC"] = "Ändert die Symbolgröße" -- Needs review
L["OPT_NPH_MARKER_SETTINGS"] = "Symboleinstellungen" -- Needs review
L["OPT_NPH_MARKER_X_OFFSET"] = "Horizontale Verschiebung" -- Needs review
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "Verschiebt Symbole horizontal." -- Needs review
L["OPT_NPH_MARKER_Y_OFFSET"] = "Vertikale Verschiebung" -- Needs review
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "Verschiebt Symbole vertikal." -- Needs review
L["OPT_NPH_WARNING1"] = [==[[=[|cFFFF0000WARNUNG:|r Die Namensplaketten feindlicher Einheiten sind deaktiviert. So kann kein rotes Kreuz angezeigt werden.
Du kannst die Namensplaketten aktivieren über Interface > Spiel > Namen oder durch betätigen der zugewiesenen Taste.]=]]==] -- Needs review
L["OPT_NPH_WARNING2"] = [==[[=[|cFFFF0000WARNUNG:|r Die Namensplaketten befreundeter Einheiten sind deaktiviert. So kann kein Heilersymbol angezeigt werden.
Du kannst die Namensplaketten aktivieren über Interface > Spiel > Namen oder durch betätigen der zugewiesenen Taste.]=]]==] -- Needs review
L["OPT_OFF"] = "aus"
L["OPT_OFF_DESC"] = "Deaktiviert HHTD"
L["OPT_ON"] = "an"
L["OPT_ON_DESC"] = "Aktiviert HHTD"
L["OPT_POST_ANNOUNCE_CHANNEL"] = "Kanal" -- Needs review
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "In diesem Kanal werden die Meldungen gesendet." -- Needs review
L["OPT_POST_ANNOUNCE_DESCRIPTION"] = [==[[=[|cFFFF0000WICHTIG:|r Tippe |cff40ff40/hhtdp|r oder belege eine Taste um die Meldung zu senden,
befreundete Heiler zu schützen und feindliche Heiler anzugreifen.
(siehe im Spielmenü unter Optionen -> Tastaturbelegung, um eine Taste zu belegen)
]=]]==] -- Needs review
L["OPT_POST_ANNOUNCE_ENABLE"] = "Senden" -- Needs review
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "Wenn du einen feindlichen Heiler anvisierst oder die Maus über ihn bewegst, wird eine Meldung in einem bestimmten Kanal gesendet." -- Needs review
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "Nur Spieler" -- Needs review
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "Es werden keine Meldungen über NPC's gesendet." -- Needs review
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "Text für feindliche Heiler" -- Needs review
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = [==[[=[Gib eine Meldung ein, die Dein Team anstachelt feindliche Heiler anzugreifen.

Du must das Schlüsselwort [HEALERS] irgendwo verwenden, welches automatisch mit den Namen der feindlichen Heiler ersetzt wird.]=]]==] -- Needs review
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "Es gibt eine Meldung für befreundete Heiler und eine für feindliche Heiler, die dürfen nicht gleich sein." -- Needs review
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "Deine Meldung ist zu kurz!" -- Needs review
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "Das Schlüsselwort [HEALERS] fehlt!" -- Needs review
L["OPT_POST_ANNOUNCE_NUMBER"] = "Anzahl Heiler" -- Needs review
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "So viele Heiler werden maximal pro Meldung einbezogen." -- Needs review
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "In einem der Texte ist ein Fehler." -- Needs review
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "Text für befreundete Heiler" -- Needs review
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = [==[[=[Gib eine Meldung ein, die Dein Team anstachelt seine Heiler zu schützen.

Du must das Schlüsselwort [HEALERS] irgendwo verwenden, welches automatisch mit den Namen der befreundeten Heiler ersetzt wird.]=]]==] -- Needs review
L["OPT_POST_ANNOUNCE_SETTINGS"] = "Sende-Einstellungen" -- Needs review
L["OPT_POST_ANNOUNCE_THROTTLE"] = "Verzögerung" -- Needs review
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "So viele Sekunden liegen mindestens zwischen den Meldungen." -- Needs review
L["OPT_PVE"] = "PVE-Option aktivieren"
L["OPT_PVE_DESC"] = "HHTD wird NPCs einbeziehen"
L["OPT_PVPHEALERSSPECSONLY"] = "Heiler Spezialisierungserkennung"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "Erkenne nur Spieler die in Heilung spezialisiert sind. (Dies deaktiviert den \"Minimale Menge an Heilung\" Filter für PVP.)"
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "Rolle befreundeter Heiler setzen" -- Needs review
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "Legt automatisch die Schlachtzug-Heiler-Rolle bei erkannten freundlichen Heilern (wenn möglich) fest." -- Needs review
L["OPT_SOUNDS"] = "Warnsignal" -- Needs review
L["OPT_SOUNDS_DESC"] = "HHTD wird einen bestimmten Sound abspielen, wenn du auf einen feindlichen Heiler zielst oder die Maus über ihn bewegst."
L["OPT_STRICTGUIDPVE"] = "Genaue PVE-Erkennung"
L["OPT_STRICTGUIDPVE_DESC"] = "Bei namensgleichen NPCs wird HHTD nur solchen NPCs ein rotes Kreuz hinzufügen, welche auch tatsächlich geheilt haben und nicht allen. Denke daran, daß Du meistens den NPC im Ziel haben oder mit der Maus darüber fahren mußt, damit das Kreuz erscheint."
L["OPT_TESTONTARGET"] = "Verhalten von HHTD auf das momentane Ziel testen" -- Needs review
L["OPT_TESTONTARGET_DESC"] = "Markiert das momentane Ziel als Heiler, so könnt Ihr testen, was passiert." -- Needs review
L["OPT_TESTONTARGET_ENOTARGET"] = "Ihr habt kein Ziel." -- Needs review
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "Benutze den \"Minimale Menge an Heilung\" Filter"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Heiler müssen für die genannte Menge heilen, bevor sie als solche markiert werden."
L["OPT_VERSION"] = "Version"
L["OPT_VERSION_DESC"] = "Version und Veröffentlichungsdatum anzeigen"
L["PARTY"] = "CHAT_MSG_PARTY" -- Needs review
L["RELEASE_DATE"] = "Veröffentlichungsdatum: "
L["SAY"] = "CHAT_MSG_SAY" -- Needs review
L["VERSION"] = "Version:"
L["YELL"] = "CHAT_MSG_YELL" -- Needs review
L["YOU_GOT_HER"] = "Du hast %ssie|r!"
L["YOU_GOT_HIM"] = "Du hast %sihn|r!"
L["YOU_GOT_IT"] = "Du hast %ses|r!"

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "esES");

    if L then
        L["ACTIVE"] = "¡Activo!" -- Needs review
L["Announcer"] = "Anunciador"
L["Announcer_DESC"] = "Este módulo te permite gestionar las alertas de chat y sonido."
-- L["AUTO_RAID_PARTY_INSTANCE"] = ""
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "Los anuncios a mensajes de raid no están configurados. Teclea /HHTDG" -- Needs review
-- L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = ""
L["CHAT_POST_NO_HEALERS"] = "No hay sanadores en ninguno de los bandos :/ (aún)" -- Needs review
L["DESCRIPTION"] = "¡Descubre a esos sanadores sangrientos instantáneamente y ayúdales a cumplir su destino! (JcE y JcJ)" -- Needs review
L["DISABLED"] = [=[hhtd ha sido desactivado!
Escribe /hhtd enable para reactivarlo.]=] -- Needs review
L["ENABLED"] = "¡Activado! Escribe /HHTDG para una lista de opciones." -- Needs review
L["HEALER_UNDER_ATTACK"] = "El sanador amigo %s esta siendo atacado por %s" -- Needs review
-- L["HUMAN"] = ""
L["IDLE"] = "Inactivo" -- Needs review
-- L["INSTANCE_CHAT"] = ""
L["IS_A_HEALER"] = "¡%s es un sanador!"
L["LOG_ACTIVE"] = "¡Activo!" -- Needs review
-- L["LOG_BELOW_THRESHOLD"] = ""
L["LOG_IDLE"] = "Inactivo" -- Needs review
L["NO_DATA"] = "No hay datos" -- Needs review
-- L["NPC"] = ""
-- L["NPH"] = ""
L["NPH_DESC"] = "Este módulo añade una cruz roja a las placas de nombre de los sanadores enemigos."
L["OPT_ANNOUNCE"] = "Mostrar mensajes"
L["OPT_ANNOUNCE_DESC"] = "HHTD mostrará mensajes cuando selecciones o pases por encima el ratón de un sanador enemigo."
L["OPT_CLEAR_LOGS"] = "Limpiar registros." -- Needs review
L["OPT_CORE_OPTIONS"] = "Opciones principales"
L["OPT_DEBUG"] = "Depurar"
L["OPT_DEBUG_DESC"] = "Activa / desactiva la depuración de errores"
-- L["OPT_DEBUGLEVEL"] = ""
-- L["OPT_DEBUGLEVEL_DESC"] = ""
L["OPT_ENABLE_GEHR"] = "Activa el Informe Gráfico"
L["OPT_ENABLE_GEHR_DESC"] = "Muestra una lista gráfica de sanadores enemigos detectados con diversas funciones"
L["OPT_HEALER_FORGET_TIMER"] = "Contador de olvido de sanador"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Establece el Contador de olvido de sanador (el tiempo en segundos en que un enemigo sigue siendo considerado como un sanador)"
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Los sanadores no serán detectados hasta que alcancen esta cantidad de sanación basada en un porcentaje de tu salud máxima." -- Needs review
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "Protege los sanadores amigos" -- Needs review
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "Muestra un mensaje cuando un sanador amigo cercano está siendo atacado" -- Needs review
L["OPT_LOG"] = "Registrando" -- Needs review
L["OPT_LOG_DESC"] = "Activa los registros y añade una nueva pestaña \"Registros\" al panel de opciones de HHTD." -- Needs review
L["OPT_LOGS"] = "Registros" -- Needs review
L["OPT_LOGS_DESC"] = "Muestra los sanadores detectados por HHTD y las estadísticas." -- Needs review
L["OPT_MODULES"] = "Módulos"
L["OPT_NPH_MARKER_SCALE"] = "Escala de los marcadores" -- Needs review
L["OPT_NPH_MARKER_SCALE_DESC"] = "Cambiar el tamaño de los marcadores" -- Needs review
L["OPT_NPH_MARKER_SETTINGS"] = "Opciones de los marcadores" -- Needs review
L["OPT_NPH_MARKER_X_OFFSET"] = "Punto horizontal" -- Needs review
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "Mueve el marcador horizontalmente" -- Needs review
L["OPT_NPH_MARKER_Y_OFFSET"] = "Punto vertical" -- Needs review
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "Mueve el marcador verticalmente" -- Needs review
L["OPT_NPH_WARNING1"] = [=[AVISO: Las placas de nombre de enemigos están desactivadas. HHTD no puede añadir el símbolo de sanador.
Puedes activar las placas de nombre a través de las opciones de interfaz de WoW o usando la tecla asignada.]=] -- Needs review
L["OPT_NPH_WARNING2"] = [=[AVISO: Las placas de nombre de aliados están desactivadas. HHTD no puede añadir el símbolo de sanador.
Puedes activar las placas de nombre a través de las opciones de interfaz de WoW o usando la tecla asignada.]=] -- Needs review
-- L["OPT_OFF"] = ""
L["OPT_OFF_DESC"] = "Desactiva HHTD"
-- L["OPT_ON"] = ""
L["OPT_ON_DESC"] = "Activa HHTD"
-- L["OPT_POST_ANNOUNCE_CHANNEL"] = ""
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "Decide donde será mostrado tu anuncio" -- Needs review
-- L["OPT_POST_ANNOUNCE_DESCRIPTION"] = ""
L["OPT_POST_ANNOUNCE_ENABLE"] = "Anuncios de chat" -- Needs review
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "Activar anuncios a raid." -- Needs review
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "Solo humanos" -- Needs review
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "No incluir NPCs en el anuncio." -- Needs review
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "Texto para sanadores enemigos" -- Needs review
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = [=[Escribe un mensaje incitando a tu equipo a centrarse en los sanadores enemigos.

Debes usar la palabra clave [SANADORES] en algún sitio, que será reemplazado automáticamente por los nombres de los sanadores activos.]=] -- Needs review
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "Hay un mensaje para amigos y otro para enemigos, no pueden ser el mismo." -- Needs review
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "¡Tu mensaje es demasiado corto!" -- Needs review
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "¡La palabra clave [SANADORES] falta!" -- Needs review
L["OPT_POST_ANNOUNCE_NUMBER"] = "Número de sanadores" -- Needs review
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "Establecer cuántos sanadores incluir en cada anuncio." -- Needs review
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "Hay algo mal con uno de los textos de anuncio." -- Needs review
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "Texto para sanadores amigos." -- Needs review
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = [=[Escribe un mensaje incitando a tu equipo a proteger sus sanadores.

Debes usar la palabra clave [SANADORES] en algún sitio, que será reemplazado automáticamente por los nombres de los sanadores activos.]=] -- Needs review
L["OPT_POST_ANNOUNCE_SETTINGS"] = "Opciones de anuncios a raid" -- Needs review
-- L["OPT_POST_ANNOUNCE_THROTTLE"] = ""
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "Establecer el tiempo mínimo en segundos entre cada posible anuncio." -- Needs review
L["OPT_PVE"] = "Activar para PVE"
L["OPT_PVE_DESC"] = "HHTD también trabajará con NPCs."
L["OPT_PVPHEALERSSPECSONLY"] = "Detección de especialización de sanador" -- Needs review
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "Solo detectar jugadores especializados en sanación. (Esto desactiva el filtro de cantidad de sanación mínima para JcJ)" -- Needs review
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "Establecer rol de los sanadores amigos" -- Needs review
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "Establecerá automáticamente el rol de raid SANADOR a los sanadores amigos cuando se detecten (si es posible)" -- Needs review
L["OPT_SOUNDS"] = "Sonidos de alerta"
L["OPT_SOUNDS_DESC"] = "HHTD activará un sonido específico cuando selecciones o pases el ratón por encima de un sanador enemigo"
L["OPT_STRICTGUIDPVE"] = "Detección refinada para PVE"
L["OPT_STRICTGUIDPVE_DESC"] = "Cuando varios NPCs compartan el mismo nombre, HHTD solo añadirá una cruz sobre aquellos que realmente curaron en vez de a todos. Toma nota de que la mayor parte del tiempo, necesitarás seleccionar o pasar el ratón por encima para que aparezca la cruz."
L["OPT_TESTONTARGET"] = "Probar el comportamiento de HHTD en el objetivo actual" -- Needs review
L["OPT_TESTONTARGET_DESC"] = "Marcará tu objetivo actual como sanador para que puedas probar lo que pasa." -- Needs review
L["OPT_TESTONTARGET_ENOTARGET"] = "Debes tener algún objetivo." -- Needs review
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "Usar filtro de cantidad sanación mínima." -- Needs review
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Los sanadores tendrán que curar una cantidad especificada antes de ser etiquetados como sanadores." -- Needs review
L["OPT_VERSION"] = "Versión"
L["OPT_VERSION_DESC"] = "Muestra la versión y la fecha de publicación"
L["PARTY"] = "Grupo" -- Needs review
L["RELEASE_DATE"] = "Fecha de publicación:"
L["SAY"] = "Decir" -- Needs review
L["VERSION"] = "Versión:"
L["YELL"] = "Gritar" -- Needs review
-- L["YOU_GOT_HER"] = ""
-- L["YOU_GOT_HIM"] = ""
-- L["YOU_GOT_IT"] = ""

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "esMX");

    if L then
        -- L["ACTIVE"] = ""
-- L["Announcer"] = ""
-- L["Announcer_DESC"] = ""
-- L["AUTO_RAID_PARTY_INSTANCE"] = ""
-- L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = ""
-- L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = ""
-- L["CHAT_POST_NO_HEALERS"] = ""
-- L["DESCRIPTION"] = ""
-- L["DISABLED"] = ""
-- L["ENABLED"] = ""
-- L["HEALER_UNDER_ATTACK"] = ""
-- L["HUMAN"] = ""
-- L["IDLE"] = ""
-- L["INSTANCE_CHAT"] = ""
-- L["IS_A_HEALER"] = ""
-- L["LOG_ACTIVE"] = ""
-- L["LOG_BELOW_THRESHOLD"] = ""
-- L["LOG_IDLE"] = ""
-- L["NO_DATA"] = ""
-- L["NPC"] = ""
-- L["NPH"] = ""
-- L["NPH_DESC"] = ""
-- L["OPT_ANNOUNCE"] = ""
-- L["OPT_ANNOUNCE_DESC"] = ""
-- L["OPT_CLEAR_LOGS"] = ""
-- L["OPT_CORE_OPTIONS"] = ""
-- L["OPT_DEBUG"] = ""
-- L["OPT_DEBUG_DESC"] = ""
-- L["OPT_DEBUGLEVEL"] = ""
-- L["OPT_DEBUGLEVEL_DESC"] = ""
-- L["OPT_ENABLE_GEHR"] = ""
-- L["OPT_ENABLE_GEHR_DESC"] = ""
-- L["OPT_HEALER_FORGET_TIMER"] = ""
-- L["OPT_HEALER_FORGET_TIMER_DESC"] = ""
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = ""
-- L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = ""
-- L["OPT_LOG"] = ""
-- L["OPT_LOG_DESC"] = ""
-- L["OPT_LOGS"] = ""
-- L["OPT_LOGS_DESC"] = ""
-- L["OPT_MODULES"] = ""
-- L["OPT_NPH_MARKER_SCALE"] = ""
-- L["OPT_NPH_MARKER_SCALE_DESC"] = ""
-- L["OPT_NPH_MARKER_SETTINGS"] = ""
-- L["OPT_NPH_MARKER_X_OFFSET"] = ""
-- L["OPT_NPH_MARKER_X_OFFSET_DESC"] = ""
-- L["OPT_NPH_MARKER_Y_OFFSET"] = ""
-- L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = ""
-- L["OPT_NPH_WARNING1"] = ""
-- L["OPT_NPH_WARNING2"] = ""
-- L["OPT_OFF"] = ""
-- L["OPT_OFF_DESC"] = ""
-- L["OPT_ON"] = ""
-- L["OPT_ON_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_CHANNEL"] = ""
-- L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_DESCRIPTION"] = ""
-- L["OPT_POST_ANNOUNCE_ENABLE"] = ""
-- L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = ""
-- L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = ""
-- L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = ""
-- L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = ""
-- L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = ""
-- L["OPT_POST_ANNOUNCE_NUMBER"] = ""
-- L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = ""
-- L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = ""
-- L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_SETTINGS"] = ""
-- L["OPT_POST_ANNOUNCE_THROTTLE"] = ""
-- L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = ""
-- L["OPT_PVE"] = ""
-- L["OPT_PVE_DESC"] = ""
-- L["OPT_PVPHEALERSSPECSONLY"] = ""
-- L["OPT_PVPHEALERSSPECSONLY_DESC"] = ""
-- L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = ""
-- L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = ""
-- L["OPT_SOUNDS"] = ""
-- L["OPT_SOUNDS_DESC"] = ""
-- L["OPT_STRICTGUIDPVE"] = ""
-- L["OPT_STRICTGUIDPVE_DESC"] = ""
-- L["OPT_TESTONTARGET"] = ""
-- L["OPT_TESTONTARGET_DESC"] = ""
-- L["OPT_TESTONTARGET_ENOTARGET"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_VERSION"] = ""
-- L["OPT_VERSION_DESC"] = ""
-- L["PARTY"] = ""
-- L["RELEASE_DATE"] = ""
-- L["SAY"] = ""
-- L["VERSION"] = ""
-- L["YELL"] = ""
-- L["YOU_GOT_HER"] = ""
-- L["YOU_GOT_HIM"] = ""
-- L["YOU_GOT_IT"] = ""

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "koKR");

    if L then
        L["ACTIVE"] = "활성화!"
L["Announcer"] = "알림"
L["Announcer_DESC"] = "이 모듈은 대화창 알림과 소리 경고를 관리할 수 있습니다."
-- L["AUTO_RAID_PARTY_INSTANCE"] = ""
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "공격대 메시지로 알리기가 설정되어 있지 않습니다. /HHTDG를 치세요."
L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = "잠깐! 기다리세요. (알림 속도 설정을 참조하세요.)"
L["CHAT_POST_NO_HEALERS"] = "아직 양쪽 힐러를 알 수 없음."
-- L["DESCRIPTION"] = ""
L["DISABLED"] = "hhtd가 중지 되었습니다! '/hhtd on'를 치면 다시 사용할 수 있습니다."
L["ENABLED"] = "사용! 옵션 목록을 보려면 /HHTDG 를 치세요." -- Needs review
L["HEALER_UNDER_ATTACK"] = "힐러 %s|1이;가; %s의 공격을 받고 있습니다."
L["HUMAN"] = "인간"
L["IDLE"] = "놀고 있음"
-- L["INSTANCE_CHAT"] = ""
L["IS_A_HEALER"] = "%s|1는;은; 힐러입니다!"
L["LOG_ACTIVE"] = "활성화!" -- Needs review
-- L["LOG_BELOW_THRESHOLD"] = ""
L["LOG_IDLE"] = "비활성화" -- Needs review
L["NO_DATA"] = "자료 없음"
L["NPC"] = "NPC"
L["NPH"] = "이름표에 표시"
L["NPH_DESC"] = "이 모듈은 적 힐러 이름표에 붉은 십자가를 표시합니다."
L["OPT_ANNOUNCE"] = "메시지 보기"
L["OPT_ANNOUNCE_DESC"] = "적 힐러를 대상으로 잡거나 마우스-오버 하면 HHTD에 메시지를 표시합니다."
L["OPT_CLEAR_LOGS"] = "기록 지우기"
L["OPT_CORE_OPTIONS"] = "코어 옵션"
L["OPT_DEBUG"] = "디버그"
L["OPT_DEBUG_DESC"] = "디버그를 사용 / 중지합니다."
-- L["OPT_DEBUGLEVEL"] = ""
-- L["OPT_DEBUGLEVEL_DESC"] = ""
L["OPT_ENABLE_GEHR"] = "그래픽 보고 사용"
L["OPT_ENABLE_GEHR_DESC"] = "다양한 기능과 함께 감지된 적 힐러를 그래픽으로 목록을 표시합니다."
L["OPT_HEALER_FORGET_TIMER"] = "힐러 표시 시간"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "힐러 표시 시간 설정 (적 힐러 표시를 유지할 시간을 초 단위로 설정합니다.)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "치유량 (|cff00dd00%u|r) 한계값"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "그것은 자신의 최대 체력의 일정 비율에 따라 치유의 누적량에 도달할 때까지 힐러가 감지되지 않습니다." -- Needs review
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "아군 힐러 보호"
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "근처의 아군 힐러가 공격받을 때 경고 표시를 합니다."
L["OPT_LOG"] = "기록하기"
L["OPT_LOG_DESC"] = "기록하기를 활성화하면 HHTD에 옵션 패널에 새로운 '기록' 탭이 추가됩니다."
L["OPT_LOGS"] = "기록"
L["OPT_LOGS_DESC"] = "감지된 힐러 및 통계를 HHTD에 표시"
L["OPT_MODULES"] = "모듈"
L["OPT_NPH_MARKER_SCALE"] = "힐러 기호 확대"
L["OPT_NPH_MARKER_SCALE_DESC"] = "힐러 기호 크기"
L["OPT_NPH_MARKER_SETTINGS"] = "힐러 기호 설정"
L["OPT_NPH_MARKER_X_OFFSET"] = "수평 위치"
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "힐러 기호의 위치를 수평으로 이동합니다."
L["OPT_NPH_MARKER_Y_OFFSET"] = "수직 위치"
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "힐러 기호의 위치를 수직으로 이동합니다."
L["OPT_NPH_WARNING1"] = "경고: 적대적 이름표는 현재 비활성화되어 있습니다. HHTD에는 붉은 십자가 기호를 추가할 수 없습니다. 와우 UI의 옵션이나 지정된 단축키를  사용하여 이름표 표시 기능을 사용할 수 있습니다."
L["OPT_NPH_WARNING2"] = "경고: 우호적 이름표는 현재 비활성화되어 있습니다. HHTD에는 힐러 기호를 추가할 수 없습니다. 와우 UI의 옵션이나 지정된 단축키를 사용하여 이름표 표시 기능을 사용할 수 있습니다."
L["OPT_OFF"] = "끄기"
L["OPT_OFF_DESC"] = "HHTD 중지."
L["OPT_ON"] = "켜기"
L["OPT_ON_DESC"] = "HHTD 사용."
L["OPT_POST_ANNOUNCE_CHANNEL"] = "알림 채널"
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "알림이 표시되는 채널을 지정합니다."
L["OPT_POST_ANNOUNCE_DESCRIPTION"] = "|cFFFF0000중요:|r 아군 힐러 보호하기와 주시할 적 힐러를 알리기 위해서는 |cff40ff40/hhtdp|r 치거나 단축키를 씁니다. (World of Warcraft에서 escape를 누르고 환경 설정 메뉴 중 단축키 설정에서 단축키를 지정합니다.)"
L["OPT_POST_ANNOUNCE_ENABLE"] = "대화창에 알리기 (/HHTDP)"
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "공격대 및 전장에 알립니다."
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "인간만 표시"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "알림에서 NPCs를 제외합니다."
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "적 힐러에 대한 문자 표시"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = "적 힐러를 주시하여 팀에 부추기는 메시지를 입력합니다. 자동으로 현재 활성화된 힐러의 이름으로 대체하려면 [HEALERS] 키워드를 사용해야 합니다."
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "적과 아군에 대해 각자 단일 메시지가 있습니다, 그들은 같을 수 없습니다."
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "메시지가 너무 짧습니다!"
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "[HEALERS] 키워드가 없습니다!"
L["OPT_POST_ANNOUNCE_NUMBER"] = "힐러 숫자"
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "각 알림에 포함할 힐러 수를 설정합니다."
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "알림 문자 중 하나에 어떤 문제가 있습니다."
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "아군 힐러에 대한 문자"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = "아군 힐러를 보호하기 위해 팀에 부추기는 메시지를 입력합니다. 자동으로 현재 활성화된 힐러의 이름으로 대체하려면 [HEALERS] 키워드를 사용해야 합니다."
L["OPT_POST_ANNOUNCE_SETTINGS"] = "공격대 알림 설정"
L["OPT_POST_ANNOUNCE_THROTTLE"] = "알림 속도 조절"
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "알림을 초 단위로 최소 시간을 설정합니다."
L["OPT_PVE"] = "PVE에서 사용."
L["OPT_PVE_DESC"] = "HHTD에서는 NPCs에 대해서도 동작합니다."
L["OPT_PVPHEALERSSPECSONLY"] = [=[힐러 특화 감지
]=]
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "오직 치료를 전문으로 하는 플레이어를 감지합니다. (이것은 PVP에 대해 최소 치유량 필터 사용을 중지합니다.)"
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "아군 힐러 역할을 설정"
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "자동 감지할 때 아군 힐러를 공격대 힐러 역할로 설정합니다. (가능한 경우)"
L["OPT_SOUNDS"] = "소리로 경고"
L["OPT_SOUNDS_DESC"] = "적 힐러를 대상으로 잡거나 마우스-오버 하면 HHTD에서는 특정 소리를 냅니다."
L["OPT_STRICTGUIDPVE"] = "정확하게 PVE 감지"
-- L["OPT_STRICTGUIDPVE_DESC"] = ""
-- L["OPT_TESTONTARGET"] = ""
-- L["OPT_TESTONTARGET_DESC"] = ""
L["OPT_TESTONTARGET_ENOTARGET"] = "적절한 대상이 필요합니다."
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "최소 치유량 필터를 사용."
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "힐러와 같은 태그에 지정되기 전에 요구된 양을 치료해야 합니다."
L["OPT_VERSION"] = "버전"
L["OPT_VERSION_DESC"] = "버전과 정식 날짜 표시"
L["PARTY"] = "파티"
L["RELEASE_DATE"] = "정식 날짜:"
L["SAY"] = "말하기"
L["VERSION"] = "버전:"
L["YELL"] = "외치기"
L["YOU_GOT_HER"] = "You got %sher|r!" -- Needs review
L["YOU_GOT_HIM"] = "You got %shim|r!" -- Needs review
L["YOU_GOT_IT"] = "You got %sit|r!" -- Needs review

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "zhCN");

    if L then
        L["ACTIVE"] = "激活！"
L["Announcer"] = "通报"
L["Announcer_DESC"] = "此模管理聊天和音效警报"
L["AUTO_RAID_PARTY_INSTANCE"] = "自动：团队/小队/副本"
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "未配置团队通报信息。输入 /HHTDG"
L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = "太快了（查看通报阈值设置）。"
L["CHAT_POST_NO_HEALERS"] = "哇靠，当前双方都没有治疗职业！:D（暂时的）"
L["DESCRIPTION"] = "立刻曝光那些该死的治疗并帮助他们走完自己的使命！（PvP 和 PvE）"
L["DISABLED"] = [=[hhtd 已被禁用！
输入“/hhtd on”来重新启用。]=]
L["ENABLED"] = "已启用！输入 /HHTDG 打开选项列表"
L["HEALER_UNDER_ATTACK"] = "友方治疗职业%s被%s攻击"
L["HUMAN"] = "人类"
L["IDLE"] = "发呆"
L["INSTANCE_CHAT"] = "副本消息"
L["IS_A_HEALER"] = "%s是治疗职业！"
L["LOG_ACTIVE"] = "激活！"
L["LOG_BELOW_THRESHOLD"] = "（低于阈值）"
L["LOG_IDLE"] = "发呆"
L["NO_DATA"] = "无数据"
L["NPC"] = "NPC"
L["NPH"] = "姓名版挂钩"
L["NPH_DESC"] = "此模块在敌对治疗姓名板上添加一个红十字"
L["OPT_ANNOUNCE"] = "显示信息"
L["OPT_ANNOUNCE_DESC"] = "当你的目标或是鼠标指向一个敌对治疗者时 HHTD 将显示信息。"
L["OPT_CLEAR_LOGS"] = "清除记录"
L["OPT_CORE_OPTIONS"] = "核心选项"
L["OPT_DEBUG"] = "除错"
L["OPT_DEBUG_DESC"] = "启用/禁用除错"
L["OPT_DEBUGLEVEL"] = "除错等级"
L["OPT_DEBUGLEVEL_DESC"] = "除错等级：1=全部，2=警报，3=错误"
L["OPT_ENABLE_GEHR"] = "启用图形报告"
L["OPT_ENABLE_GEHR_DESC"] = "显示敌对治疗多功能图形列表"
L["OPT_HEALER_FORGET_TIMER"] = "治疗职业遗忘计时器"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "设置治疗职业遗忘计时器（用于在一定时间内将一个敌人标记为治疗职业）"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "治疗值（|cff00dd00%u|r）阈值"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "治疗职业当他们达到累积的治疗量根据自己的最大生命值的百分比之前不会被检测到。"
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "保护友方治疗职业"
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "当附近的友方治疗职业被攻击时显示警报"
L["OPT_LOG"] = "正在记录"
L["OPT_LOG_DESC"] = "启用记录并添加一个新的“记录”标签到 HHTD 选项面板"
L["OPT_LOGS"] = "记录"
L["OPT_LOGS_DESC"] = "显示 HHTD 检测到的治疗和数据"
L["OPT_MODULES"] = "模块"
L["OPT_NPH_MARKER_SCALE"] = "标记缩放"
L["OPT_NPH_MARKER_SCALE_DESC"] = "更改标记尺寸"
L["OPT_NPH_MARKER_SETTINGS"] = "标记配置"
L["OPT_NPH_MARKER_X_OFFSET"] = "水平偏移量"
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "水平移动标记"
L["OPT_NPH_MARKER_Y_OFFSET"] = "垂直偏移量"
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "垂直移动标记"
L["OPT_NPH_WARNING1"] = [=[提示：敌方姓名版未被启用。HHTD 不能添加治疗标记。
可以通过游戏内界面选项开启姓名版显示或使用快捷键。]=]
L["OPT_NPH_WARNING2"] = [=[提示：友方姓名版未被启用。HHTD 不能添加治疗标记。
可以通过游戏内界面选项开启姓名版显示或使用快捷键。]=]
L["OPT_OFF"] = "off"
L["OPT_OFF_DESC"] = "禁用 HHTD"
L["OPT_ON"] = "on"
L["OPT_ON_DESC"] = "启用 HHTD"
L["OPT_POST_ANNOUNCE_CHANNEL"] = "广播频道"
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "选择广播通报的频道"
L["OPT_POST_ANNOUNCE_DESCRIPTION"] = [=[|cFFFF0000主要：|r输入 |cff40ff40/hhtdp|r 或绑定按键通报保护友方治疗职业和特殊照顾敌方治疗职业。

（魔兽世界 ESC 菜单绑定界面设置按键绑定）]=]
L["OPT_POST_ANNOUNCE_ENABLE"] = "聊天通报"
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "启用通报到团队功能。"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "只对人类"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "通报中不包含 NPC。"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "敌对治疗文本"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = [=[输入一个消息鼓动你的队伍集中火力攻击敌方治疗职业。

必须使用 [HEALERS] 键值将被自动替换为当前激活治疗职业。]=]
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "这有一个友好和敌对的信息，他们不能一样。"
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "你的信息太少了！"
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "[HEALERS] 键值缺失！"
L["OPT_POST_ANNOUNCE_NUMBER"] = "治疗数量"
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "设置每条通报上的治疗数量。"
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "通报文本里有什么东西出错。"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "友方治疗文本"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = [=[输入一个信息鼓动团队保护他们的治疗职业。

必须使用 [HEALERS] 键值将被自动替换为当激活的治疗职业。]=]
L["OPT_POST_ANNOUNCE_SETTINGS"] = "通报到团队设置"
L["OPT_POST_ANNOUNCE_THROTTLE"] = "通报阈值"
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "设置每条可能通报的最小时间间隔。"
L["OPT_PVE"] = "PvE 启用"
L["OPT_PVE_DESC"] = "HHTD 同样作用于 NPC。"
L["OPT_PVPHEALERSSPECSONLY"] = "治疗职业特定检测"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "只特定治疗玩家。（此项禁用 PvP 最小治疗量）"
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "设置友方治疗职业角色"
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "（如可能）自动设置检测团队治疗角色到友方治疗"
L["OPT_SOUNDS"] = "音效警报"
L["OPT_SOUNDS_DESC"] = "当你鼠标悬停或目标到一个敌对治疗时 HHTD 播放特定的音效。"
L["OPT_STRICTGUIDPVE"] = "精确 PvE 检测"
L["OPT_STRICTGUIDPVE_DESC"] = "当多个 NPC 共享相同的名称，HHTD 只会增加一个十字而不是全部。请注意，在十字出现之前大部分的时间需要切换目标或鼠标悬停在单位。"
L["OPT_TESTONTARGET"] = "在当前目标测试 HHTD 状态"
L["OPT_TESTONTARGET_DESC"] = "将标记当前目标为治疗者来测试发生了什么。"
L["OPT_TESTONTARGET_ENOTARGET"] = "需要一个目标"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "使用最少治疗值过滤"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "治疗职业将有指定治疗数值前被标记等。"
L["OPT_VERSION"] = "version"
L["OPT_VERSION_DESC"] = "显示版本和发布日期"
L["PARTY"] = "小队"
L["RELEASE_DATE"] = "发布日期："
L["SAY"] = "说"
L["VERSION"] = "版本："
L["YELL"] = "大喊"
L["YOU_GOT_HER"] = "你抓到%s她了|r！"
L["YOU_GOT_HIM"] = "你抓到%s他了|r！"
L["YOU_GOT_IT"] = "你抓到%s它了|r！"

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "zhTW");

    if L then
        L["ACTIVE"] = "啟動！"
L["Announcer"] = "通報"
L["Announcer_DESC"] = "此模組管理聊天和音效警報"
L["AUTO_RAID_PARTY_INSTANCE"] = "自動:團隊/隊伍/副本"
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "未配置團隊通報訊息。輸入 /HHTDG"
L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = "太快了（查看通報閾值設置）。"
L["CHAT_POST_NO_HEALERS"] = "哇靠，當前雙方都沒有治療！"
L["DESCRIPTION"] = "立刻曝光那些該死的治療並幫助他們走完自己的使命！（PvP 和 PvE）"
L["DISABLED"] = [=[hhtd 已被禁用！
輸入“/hhtd on”來重新啟用。]=]
L["ENABLED"] = "已啟用！輸入 /HHTDG 開啟選項面板"
L["HEALER_UNDER_ATTACK"] = "友方治療者%s被%s攻擊"
L["HUMAN"] = "人類"
L["IDLE"] = "呆滯"
L["INSTANCE_CHAT"] = "副本頻道"
L["IS_A_HEALER"] = "%s是治療者！"
L["LOG_ACTIVE"] = "啟動！"
L["LOG_BELOW_THRESHOLD"] = "（低於閾值）"
L["LOG_IDLE"] = "呆滯"
L["NO_DATA"] = "無數據"
L["NPC"] = "NPC"
L["NPH"] = "姓名版掛鉤"
L["NPH_DESC"] = "此模組在敵方治療者姓名板上添加一個紅十字"
L["OPT_ANNOUNCE"] = "顯示訊息"
L["OPT_ANNOUNCE_DESC"] = "當你的目標或是鼠標指向一個敵對治療者時 HHTD 將顯示訊息。"
L["OPT_CLEAR_LOGS"] = "清除記錄"
L["OPT_CORE_OPTIONS"] = "核心選項"
L["OPT_DEBUG"] = "除錯"
L["OPT_DEBUG_DESC"] = "啟用/禁用除錯"
L["OPT_DEBUGLEVEL"] = "除錯等級"
L["OPT_DEBUGLEVEL_DESC"] = "除錯等級：1=全部，2 =警報，3 =錯誤"
L["OPT_ENABLE_GEHR"] = "啟用圖形報告"
L["OPT_ENABLE_GEHR_DESC"] = "顯示敵對治療多功能圖形列表"
L["OPT_HEALER_FORGET_TIMER"] = "治療忽略計時器"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "設置治療忽略計時器（在幾秒鐘的時間敵人仍會被認為有個治療者）"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "治療值（|cff00dd00%u|r）閾值"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "治療者不會被偵測到直到他們累積一定數額的治療量(基於你最大血量的百分比)。"
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "保護友方治療者"
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "當附近的友方治療者被攻擊時顯示警報"
L["OPT_LOG"] = "正在記錄"
L["OPT_LOG_DESC"] = "啟用記錄並添加一個新的“記錄”標籤到 HHTD 選項面板"
L["OPT_LOGS"] = "記錄"
L["OPT_LOGS_DESC"] = "顯示 HHTD 檢測到的治療和數據"
L["OPT_MODULES"] = "模塊"
L["OPT_NPH_MARKER_SCALE"] = "標記縮放"
L["OPT_NPH_MARKER_SCALE_DESC"] = "更改標記尺寸"
L["OPT_NPH_MARKER_SETTINGS"] = "標記配置"
L["OPT_NPH_MARKER_X_OFFSET"] = "水平偏移量"
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "水平移動標記"
L["OPT_NPH_MARKER_Y_OFFSET"] = "垂直偏移量"
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "垂直移動標記"
L["OPT_NPH_WARNING1"] = [=[警告：敵方姓名條目前是關閉的，HHTD無法加入紅十字標誌。
你可以在WoW的介面選項裏啟用姓名條顯示，或使用指定的按鍵。]=]
L["OPT_NPH_WARNING2"] = [=[警告：友方姓名條目前是關閉的，HHTD無法加入治療者標誌。
你可以在WoW的介面選項裏啟用姓名條顯示，或使用指定的按鍵。]=]
L["OPT_OFF"] = "off"
L["OPT_OFF_DESC"] = "禁用 HHTD"
L["OPT_ON"] = "on"
L["OPT_ON_DESC"] = "啟用 HHTD"
L["OPT_POST_ANNOUNCE_CHANNEL"] = "廣播頻道"
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "選擇廣播通報的頻道"
L["OPT_POST_ANNOUNCE_DESCRIPTION"] = [=[|cFFFF0000重要:|r 輸入 |cff40ff40/hhtdp|r 或是綁定一個按鍵以通報保護友方治療者與聚焦敵方治療者。
(請看魔獸世界ESC的快捷鍵設定介面以綁定一個按鍵)]=]
L["OPT_POST_ANNOUNCE_ENABLE"] = "聊天通報"
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "啟用通報到團隊功能。"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "只對人類"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "通報中不包含 NPC。"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "敵對治療文本"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = [=[輸入一個訊息以煽動你的團隊聚焦到敵方治療者。
你必須使用 [HEALERS]關鍵字，此字會自動替換為當前敵方治療者的名稱。]=]
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "這有一個友好和敵對的訊息，他們不能一樣。"
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "你的訊息太少了！"
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "[治療]鍵值缺失！"
L["OPT_POST_ANNOUNCE_NUMBER"] = "治療數量"
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "設置每條通報上的治療數量。"
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "通報文本里有什麼東西出錯。"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "友方治療文本"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = [=[輸入一個訊息調動團隊保護他們的治療。

你必須使用[HEALERS]關鍵字，而此字將被替換為當前啟動的治療者。]=]
L["OPT_POST_ANNOUNCE_SETTINGS"] = "通報到團隊設置"
L["OPT_POST_ANNOUNCE_THROTTLE"] = "通報閾值"
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "設置每條可能通報的最小時間間隔。"
L["OPT_PVE"] = "PvE 啟用"
L["OPT_PVE_DESC"] = "HHTD 同樣作用於 NPC。"
L["OPT_PVPHEALERSSPECSONLY"] = "治療特定檢測"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "只特定治療玩家。（此項禁用 PvP 最小治療量）"
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "設置友方治療者角色"
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "（如可能）自動設置檢測團隊治療職責到友方治療"
L["OPT_SOUNDS"] = "音效警報"
L["OPT_SOUNDS_DESC"] = "當你鼠標懸停或目標到一個敵對治療時 HHTD 播放特定的音效。"
L["OPT_STRICTGUIDPVE"] = "精確 PvE 檢測"
L["OPT_STRICTGUIDPVE_DESC"] = "當幾個NPC共享相同的名稱，HHTD將只會增加一個紅十字在真實的治療者而不是所有人上。請注意大多數時間，你需要指定目標或滑鼠停留一個單位以讓十字顯示。"
L["OPT_TESTONTARGET"] = "在當前目標測試 HHTD 狀態"
L["OPT_TESTONTARGET_DESC"] = "將標記當前目標為治療者來測試發生了什麼。"
L["OPT_TESTONTARGET_ENOTARGET"] = "需要一個目標"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "使用最少治療值過濾"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "治療者需要治療特定數額的治療量才能被標記。"
L["OPT_VERSION"] = "version"
L["OPT_VERSION_DESC"] = "顯示版本和發佈日期"
L["PARTY"] = "小隊"
L["RELEASE_DATE"] = "發佈日期："
L["SAY"] = "說"
L["VERSION"] = "版本："
L["YELL"] = "大喊"
L["YOU_GOT_HER"] = "你抓到%s她了|r！"
L["YOU_GOT_HIM"] = "你抓到%s他了|r！"
L["YOU_GOT_IT"] = "你抓到%s它了|r！"

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "ruRU");

    if L then
        L["ACTIVE"] = "Активный!"
L["Announcer"] = "Информатор"
L["Announcer_DESC"] = "Модуль настройки оповещений в чате и звуковых оповещений"
-- L["AUTO_RAID_PARTY_INSTANCE"] = ""
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "Рейдовые оповещения не сконфигурированы. Введите /HHTDG"
L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = "Слишком быстро. Проверьте установки скорости появления оповещений"
L["CHAT_POST_NO_HEALERS"] = "Ни наших,ни вражеских лекарей не обнаружено :/ (Пока...)"
L["DESCRIPTION"] = "Мгновенно обнаружить этих чертовых лекарей и воздать им по заслугам! (PVP и PVE)."
L["DISABLED"] = [=[HHTD выключен.
Введите "/hhtd on" для включения.]=]
L["ENABLED"] = [=[HHTD включен!
Для просмотра возможных параметров введите команду /HHTDG]=] -- Needs review
L["HEALER_UNDER_ATTACK"] = "наш лекарь %s атакован %s"
L["HUMAN"] = "Человек"
L["IDLE"] = "Находится в режиме ожидания"
-- L["INSTANCE_CHAT"] = ""
L["IS_A_HEALER"] = "%s - лекарь!"
L["LOG_ACTIVE"] = "активен"
L["LOG_BELOW_THRESHOLD"] = "ниже порогового значения"
L["LOG_IDLE"] = "в режиме ожидания"
L["NO_DATA"] = "Информация отсутствует"
L["NPC"] = "НИП"
L["NPH"] = "Подключение к индикаторам"
L["NPH_DESC"] = "Модуль, добавляющий красный крест к индикаторам здоровья вражеских лекарей"
L["OPT_ANNOUNCE"] = "Вывод сообщений"
L["OPT_ANNOUNCE_DESC"] = "HHTD выводит сообщения при выборе вражеского лекаря в цель или наведении на него мышкой"
L["OPT_CLEAR_LOGS"] = "Стирает информацию в Логах"
L["OPT_CORE_OPTIONS"] = "Основные настройки"
L["OPT_DEBUG"] = "отладка"
L["OPT_DEBUG_DESC"] = "Включает/выключает режим отладки."
-- L["OPT_DEBUGLEVEL"] = ""
-- L["OPT_DEBUGLEVEL_DESC"] = ""
L["OPT_ENABLE_GEHR"] = "Включение графического информатора"
L["OPT_ENABLE_GEHR_DESC"] = "Отображает графический список вражеских лекарей с разными дополнительными возможностями."
L["OPT_HEALER_FORGET_TIMER"] = "Таймер забывания лекарей"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "устанавливает таймер забывания лекаря (Сколько времени в секундах помнить об обнаруженном лекаре)."
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "Порог количества лечения - (|cff00dd00%u|r)."
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Лекари не будут обнаружены, пока они не достигнут Порога количества лечения."
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "защитить наших лекарей"
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "выдать сообщение когда рядом с вами атакован наш лекарь "
L["OPT_LOG"] = "Загрузка"
L["OPT_LOG_DESC"] = "включает режим загрузки и добавляет новую страницу \"Логи\" к панели опций HHTD"
L["OPT_LOGS"] = "Логи"
L["OPT_LOGS_DESC"] = "отображает лекарей, обнаруженных HHTD, и соответствующую статистику"
L["OPT_MODULES"] = "Модули"
L["OPT_NPH_MARKER_SCALE"] = "установка пропорций индикаторов"
L["OPT_NPH_MARKER_SCALE_DESC"] = "изменить размер индикаторов"
L["OPT_NPH_MARKER_SETTINGS"] = "установка параметров индикаторов"
L["OPT_NPH_MARKER_X_OFFSET"] = "отступ по горизонтали"
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "сдвинуть маркеры по горизонтали"
L["OPT_NPH_MARKER_Y_OFFSET"] = "отступ по вертикали"
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "сдвинуть маркеры по вертикали"
L["OPT_NPH_WARNING1"] = [=[ВНИМАНИЕ: Индикаторы здоровья врагов выключены! HHTD не сможет добавлять символ красного креста!
Вы можете включить индикаторы здоровья через опции интерфейса WoW или используя горячую клавишу.]=]
L["OPT_NPH_WARNING2"] = [=[ВНИМАНИЕ: Индикаторы здоровья союзников выключены! HHTD не сможет добавлять символ лекаря!
Вы можете включить индикаторы здоровья через опции интерфейса WoW или используя горячую клавишу.]=]
L["OPT_OFF"] = "off"
L["OPT_OFF_DESC"] = "Отключение HHTD."
L["OPT_ON"] = "on"
L["OPT_ON_DESC"] = "Включает HHTD"
L["OPT_POST_ANNOUNCE_CHANNEL"] = "канал сообщения"
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "выберите в каком канале появится ваше сообщение"
L["OPT_POST_ANNOUNCE_DESCRIPTION"] = "|cFFFF0000IMPORTANT:|r Введите |cff40ff40/hhtdp|r или назначьте горячую клавишу для выдачи объявления о небходимости защиты наших лекарей, и о фокусировании на атаках на вражеских лекарей"
L["OPT_POST_ANNOUNCE_ENABLE"] = "объявления в чате"
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "Включает рейдовые оповещения"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "Только люди"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "Не включать имена НИП в оповещения"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "Текст для вражеских лекарей"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = [=[Выдать сообщение для вашей группы о необходимости сконцентрироваться на атаке вражеских лекарей.

В тексте вашего сообщения вы должны использовать кодовое слово [HEALERS], которое будет автоматически заменено на имена активных в данный момент лекарей]=]
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "Есть сообщения для друзей, и есть для недругов. Они не могут быть одинаковы."
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "ваше сообщение слишком короткое"
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "кодовое слово [HEALERS] отсутствует"
L["OPT_POST_ANNOUNCE_NUMBER"] = "количество лекарей"
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "установить какое количество лекарей включать в каждое оповещение"
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "что-то не так с текстом одного из обьявлений"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "текст для наших лекарей"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = [=[Выдать сообщение для вашей группы о необходимости сконцентрироваться на защите наших лекарей.

В тексте вашего сообщения вы должны использовать кодовое слово [HEALERS], которое будет автоматически заменено на имена активных в данный момент лекарей]=]
L["OPT_POST_ANNOUNCE_SETTINGS"] = "параметры рейдовых обьявлений"
L["OPT_POST_ANNOUNCE_THROTTLE"] = "скорость появления обьявлений"
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "установите минимальное время в секундах между появлениями каждого из возможных обьявлений"
L["OPT_PVE"] = "Включить для ПВЕ"
L["OPT_PVE_DESC"] = "Разрешить использование HHTD против НИП"
L["OPT_PVPHEALERSSPECSONLY"] = "Обнаружение специализации лекаря"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "Выявлять только игроков специализирующихся на лечении. Эта опция отключает фильтр порога количества лечения в PvP."
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "установите роли наших лекарей"
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "если возможно, автоматически установит роль Лекарь Рейда для всех обнаруженных наших лекарей"
L["OPT_SOUNDS"] = "Звуковые оповещения"
L["OPT_SOUNDS_DESC"] = "HHTD воспроизводит определенный звук при выборе лекаря в цель или наведении на него мышки"
L["OPT_STRICTGUIDPVE"] = "Точность отслеживания в ПВЕ-режиме"
L["OPT_STRICTGUIDPVE_DESC"] = "Если несколько НИП имеют одинаковые имена, HHTD добавит красный крест только к тому, который лечил в последнее время, а не ко всем сразу. В большинстве случаев понадобится выбрать НИП целью или навести на него мышь для появления креста."
L["OPT_TESTONTARGET"] = "протестировать работу HHTD на выбранной цели"
L["OPT_TESTONTARGET_DESC"] = "пометит выбранную вами цель как лекаря чтобы вы смогли протестировать как все работает"
L["OPT_TESTONTARGET_ENOTARGET"] = "вы должны сначала выбрать цель"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "Фильтр порога количества лечения."
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Лекарь должен выдать определенное количество лечения прежде чем он будет помечен как лекарь."
L["OPT_VERSION"] = "версия"
L["OPT_VERSION_DESC"] = "Информация о версии и дате релиза"
L["PARTY"] = "группа"
L["RELEASE_DATE"] = "Дата выхода:"
L["SAY"] = "сказать"
L["VERSION"] = "Версия:"
L["YELL"] = "крикнуть"
L["YOU_GOT_HER"] = "Ты сделал %sее|r!"
L["YOU_GOT_HIM"] = "Ты сделал %sего|r!"
L["YOU_GOT_IT"] = "Ты сделал %sэтого|r!"

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "itIT");

    if L then
        -- L["ACTIVE"] = ""
-- L["Announcer"] = ""
-- L["Announcer_DESC"] = ""
-- L["AUTO_RAID_PARTY_INSTANCE"] = ""
-- L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = ""
-- L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = ""
-- L["CHAT_POST_NO_HEALERS"] = ""
-- L["DESCRIPTION"] = ""
-- L["DISABLED"] = ""
-- L["ENABLED"] = ""
-- L["HEALER_UNDER_ATTACK"] = ""
-- L["HUMAN"] = ""
-- L["IDLE"] = ""
-- L["INSTANCE_CHAT"] = ""
-- L["IS_A_HEALER"] = ""
-- L["LOG_ACTIVE"] = ""
-- L["LOG_BELOW_THRESHOLD"] = ""
-- L["LOG_IDLE"] = ""
-- L["NO_DATA"] = ""
-- L["NPC"] = ""
-- L["NPH"] = ""
-- L["NPH_DESC"] = ""
-- L["OPT_ANNOUNCE"] = ""
-- L["OPT_ANNOUNCE_DESC"] = ""
-- L["OPT_CLEAR_LOGS"] = ""
-- L["OPT_CORE_OPTIONS"] = ""
-- L["OPT_DEBUG"] = ""
-- L["OPT_DEBUG_DESC"] = ""
-- L["OPT_DEBUGLEVEL"] = ""
-- L["OPT_DEBUGLEVEL_DESC"] = ""
-- L["OPT_ENABLE_GEHR"] = ""
-- L["OPT_ENABLE_GEHR_DESC"] = ""
-- L["OPT_HEALER_FORGET_TIMER"] = ""
-- L["OPT_HEALER_FORGET_TIMER_DESC"] = ""
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = ""
-- L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = ""
-- L["OPT_LOG"] = ""
-- L["OPT_LOG_DESC"] = ""
-- L["OPT_LOGS"] = ""
-- L["OPT_LOGS_DESC"] = ""
-- L["OPT_MODULES"] = ""
-- L["OPT_NPH_MARKER_SCALE"] = ""
-- L["OPT_NPH_MARKER_SCALE_DESC"] = ""
-- L["OPT_NPH_MARKER_SETTINGS"] = ""
-- L["OPT_NPH_MARKER_X_OFFSET"] = ""
-- L["OPT_NPH_MARKER_X_OFFSET_DESC"] = ""
-- L["OPT_NPH_MARKER_Y_OFFSET"] = ""
-- L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = ""
-- L["OPT_NPH_WARNING1"] = ""
-- L["OPT_NPH_WARNING2"] = ""
-- L["OPT_OFF"] = ""
-- L["OPT_OFF_DESC"] = ""
-- L["OPT_ON"] = ""
-- L["OPT_ON_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_CHANNEL"] = ""
-- L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_DESCRIPTION"] = ""
-- L["OPT_POST_ANNOUNCE_ENABLE"] = ""
-- L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = ""
-- L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = ""
-- L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = ""
-- L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = ""
-- L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = ""
-- L["OPT_POST_ANNOUNCE_NUMBER"] = ""
-- L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = ""
-- L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = ""
-- L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = ""
-- L["OPT_POST_ANNOUNCE_SETTINGS"] = ""
-- L["OPT_POST_ANNOUNCE_THROTTLE"] = ""
-- L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = ""
-- L["OPT_PVE"] = ""
-- L["OPT_PVE_DESC"] = ""
-- L["OPT_PVPHEALERSSPECSONLY"] = ""
-- L["OPT_PVPHEALERSSPECSONLY_DESC"] = ""
-- L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = ""
-- L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = ""
-- L["OPT_SOUNDS"] = ""
-- L["OPT_SOUNDS_DESC"] = ""
-- L["OPT_STRICTGUIDPVE"] = ""
-- L["OPT_STRICTGUIDPVE_DESC"] = ""
-- L["OPT_TESTONTARGET"] = ""
-- L["OPT_TESTONTARGET_DESC"] = ""
-- L["OPT_TESTONTARGET_ENOTARGET"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = ""
-- L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = ""
-- L["OPT_VERSION"] = ""
-- L["OPT_VERSION_DESC"] = ""
-- L["PARTY"] = ""
-- L["RELEASE_DATE"] = ""
-- L["SAY"] = ""
-- L["VERSION"] = ""
-- L["YELL"] = ""
-- L["YOU_GOT_HER"] = ""
-- L["YOU_GOT_HIM"] = ""
-- L["YOU_GOT_IT"] = ""

    end
end
